name: Deploy to SAP BTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: ./mvnw package -DskipTests

      - name: Install Cloud Foundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx
          sudo mv cf /usr/local/bin/
          cf --version

      - name: Login to Cloud Foundry
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          cf login -a $CF_API -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE

      - name: Deploy Application Without Starting
        run: |
          cf push SimpleIRE_Media-t1 --no-start -b https://github.com/cloudfoundry/java-buildpack.git#v4.61.0

      - name: Start the Application
        run: |
          cf start SimpleIRE_Media-t1

      - name: Logout of Cloud Foundry
        if: always()
        run: cf logout